In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data = pd.read_csv("../data/train.txt", sep=";", names=["text", "emotion"], header=None)
data.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
data.isnull().sum()

text       0
emotion    0
dtype: int64

In [6]:
data['text']=data['text'].apply(lambda x: x.lower())

In [7]:
# Remove Punctuation
import string 

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))
data['text'] = data['text'].apply(remove_punctuation)

In [8]:
data.text

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [9]:
# Remove number
def remove_numbers(text):
    return text.translate(str.maketrans('', '', string.digits))
data['text'] = data['text'].apply(remove_numbers)

In [10]:
# Remove Url and Link
import re
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)
data['text'] = data['text'].apply(remove_urls)

In [11]:
# Remove HTML tags
def remove_html_tags(text):
    html_pattern = re.compile(r'<.*?>')
    return html_pattern.sub(r'', text)
data['text'] = data['text'].apply(remove_html_tags)

In [12]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    word_tokens = word_tokenize(text)
    filtered_text = [word for word in word_tokens if word not in stop_words]
    return " ".join(filtered_text)
data['text'] = data['text'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ujjwa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ujjwa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ujjwa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [13]:
data

                                                    text  emotion
0                                  didnt feel humiliated  sadness
1      go feeling hopeless damned hopeful around some...  sadness
2              im grabbing minute post feel greedy wrong    anger
3      ever feeling nostalgic fireplace know still pr...     love
4                                        feeling grouchy    anger
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten  sadness
15996  turning feel pathetic still waiting tables sub...  sadness
15997                           feel strong good overall      joy
15998                     feel like rude comment im glad    anger
15999                       know lot feel stupid portray  sadness

[16000 rows x 2 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['emotion'] = encoder.fit_transform(data['emotion'])

In [15]:
X=data['text']
y=data['emotion']

In [16]:
X

0                                    didnt feel humiliated
1        go feeling hopeless damned hopeful around some...
2                im grabbing minute post feel greedy wrong
3        ever feeling nostalgic fireplace know still pr...
4                                          feeling grouchy
                               ...
15995        brief time beanbag said anna feel like beaten
15996    turning feel pathetic still waiting tables sub...
15997                             feel strong good overall
15998                       feel like rude comment im glad
15999                         know lot feel stupid portray
Name: text, Length: 16000, dtype: str

In [17]:
y.unique()

array([4, 0, 3, 5, 1, 2])

In [18]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
# Correct order: X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
model = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=5000,
        stop_words='english'
    )),
    ('xgb', XGBClassifier(
        objective='multi:softmax',
        num_class=len(y.unique()),
        n_estimators=200,
        learning_rate=0.1,
        max_depth=6,
        random_state=42
    ))
])

In [21]:
model.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=5000, stop_words='english')),
                ('xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None, num_class=6, ...))])

In [22]:
prdeictions = model.predict(X_test)
prdeictions

array([4, 2, 4, ..., 2, 2, 4], shape=(3200,), dtype=int32)

In [23]:
accuracy_score(y_test, prdeictions)

0.866875

In [24]:
import joblib
joblib.dump(model, 'emotion_detector_model.pkl')

['emotion_detector_model.pkl']